CREATE TABLE IF NOT EXISTS `demo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '内容',
  `createdAt` TIMESTAMP(3) NULL,
  `updatedAt` TIMESTAMP(3) NULL,
  PRIMARY KEY(`id`)
) COMMENT 'DEMO表';